server:
  port: 8080

spring:
  application:
    name: E-Commerce-Application

  datasource:
    url: jdbc:mysql://localhost:3306/ecom_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  app:
    jwtSecret: dictionary2224324uifbhfiuhbfud8958t948tihiuvhsudAHJDHJFJFNFJNJJJIJrigroeigurooisdjvdlnvjdnfkjsdhfiuehdfuidh
    jwtExpirationMS: 6000000000
    jwtCookieName: springbootEcom

logging:
  level:
    org:
      springframework: DEBUG
      springframework.security: DEBUG
      hibernate:
        sql: DEBUG
    com:
      ecommerce:
        app: DEBUG

project:
  image: images/